### PR TITLE
Update 1.26.12

### PR DESCRIPTION
**Pull request by Jrice1317**
Update to version 1.26.12

Jira ticket [PKG-185](https://anaconda.atlassian.net/browse/PKG-185)

Package Info
Home: https://urllib3.readthedocs.io/
Development: https://github.com/urllib3/urllib3
Documentation: https://urllib3.readthedocs.io/
Git diff: https://github.com/urllib3/urllib3/compare/1.26.11...1.26.12

### CODE REVIEW

**Review by varlackc — APPROVED** [review]
need to add `brotli>=1.0.9`
https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L88

need to add `brotlicffi>=0.8.0`
https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L89

everything else looks good so far.

**Comment by skupr-anaconda** [comment]
> need to add `brotli>=1.0.9` https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L88
> 
> need to add `brotlicffi>=0.8.0` https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L89
> 
> everything else looks good so far.

@varlackc These packages are optional and as a result, the package `urllib3` will be broken, see details here https://github.com/AnacondaRecipes/urllib3-feedstock/pull/3#issue-934054546

**Review by skupr-anaconda — APPROVED** [review]

**Comment by marcoesters** [comment]
> 

Maybe add a clarifying comment above the linked github issue to expand on why we are using brotlipy.

**Comment by varlackc** [comment]
> > need to add `brotli>=1.0.9` https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L88
> > need to add `brotlicffi>=0.8.0` https://github.com/urllib3/urllib3/blob/1.26.12/setup.py#L89
> > everything else looks good so far.
> 
> @varlackc These packages are optional and as a result, the package `urllib3` will be broken, see details here [#3 (comment)](https://github.com/AnacondaRecipes/urllib3-feedstock/pull/3#issue-934054546)

Thank you for pointing that out, not sure how I missed that detail.

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
