### PR TITLE
urllib3 2.0.7 (versioned)

### PR DESCRIPTION
**Pull request by lorepirri**
urllib3 2.0.7 (versioned)

**Destination channel:** **defaults**

### Links

- [PKG-3942]
- https://github.com/urllib3/urllib3/tree/2.0.7
- :warning: older version than what we have on defaults, this requires a versioned feedstock creation.

### Dependency for

- AnacondaRecipes/tableauserverclient-feedstock/pull/2

### Explanation of changes:

- versioned feedstock, `2.0.7`, this PR merges against `master-2.0.7`

[PKG-3942]: https://anaconda.atlassian.net/browse/PKG-3942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM

A small comment though: in 2.0.3 we had not included zstandard as a dependency. Keeping 2.0.7 aligned (moving zstandard to a run_constrained) would be more consistent I believe.

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by lorepirri** [comment]
> LGTM
> 
> A small comment though: in 2.0.3 we had not included zstandard as a dependency. Keeping 2.0.7 aligned (moving zstandard to a run_constrained) would be more consistent I believe.

@cbouss they are all in `run_constrained`: 

I see that in `2.0.3` they are in `run` https://github.com/AnacondaRecipes/urllib3-feedstock/pull/15/files

but in `2.1.0` they were all removed https://github.com/AnacondaRecipes/urllib3-feedstock/pull/17/files.

I will remove them from `run_constrained` if you think they are an over-pinning.

thank you for the review!

**Comment by cbouss** [comment]
> > LGTM
> > 
> > A small comment though: in 2.0.3 we had not included zstandard as a dependency. Keeping 2.0.7 aligned (moving zstandard to a run_constrained) would be more consistent I believe.
> 
> @cbouss they are all in `run_constrained`: 
> 
> I see that in `2.0.3` they are in `run` https://github.com/AnacondaRecipes/urllib3-feedstock/pull/15/files
> 
> but in `2.1.0` they were all removed https://github.com/AnacondaRecipes/urllib3-feedstock/pull/17/files.
> 
> I will remove them from `run_constrained` if you think they are an over-pinning.
> 
> thank you for the review!

Oh I hadn't looked at the section properly! We should follow the pattern of 2.0.3. So the optional security stuff in run and and zstandard in run constrained.

**Comment by lorepirri** [comment]
> > > LGTM
> > > A small comment though: in 2.0.3 we had not included zstandard as a dependency. Keeping 2.0.7 aligned (moving zstandard to a run_constrained) would be more consistent I believe.
> > 
> > 
> > @cbouss they are all in `run_constrained`:
> > I see that in `2.0.3` they are in `run` https://github.com/AnacondaRecipes/urllib3-feedstock/pull/15/files
> > but in `2.1.0` they were all removed https://github.com/AnacondaRecipes/urllib3-feedstock/pull/17/files.
> > I will remove them from `run_constrained` if you think they are an over-pinning.
> > thank you for the review!
> 
> Oh I hadn't looked at the section properly! We should follow the pattern of 2.0.3. So the optional security stuff in run and and zstandard in run constrained.

that's cool, I've followed your suggestion. I guess now it should follow your idea if I did not get it wrong.

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
